# Generated by Django 4.2.7 on 2023-11-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='equipo_futbol',
            new_name='Equipo',
        ),
    ]
